export const regexps = {
 next: [/_next/],
 googlefonts: [/fonts\.googleapis\.com/, /fonts\.gstatic\.com/],
 tailwindcss: [/MIT License \| https:\/\/tailwindcss\.com/, /--tw-/],
 bulmacss: [/bulma.io .* \| MIT License \| github.com\/jgthms\/bulma/],
 lenis: [/lenis/],
 cloudinary: [/res\.cloudinary\.com/],
 fontawesome: [/\/fontawesome/, /FortAwesome.*.css/],
 vue: [/vue-analytics/, /window\.Vue/, /\$vuetify/, /VUE_/, /_isVue/],
 react: [/https:\/\/reactjs\.org\/docs\/error-decoder\.html/, /react\.forward_ref/, /__reactInternal/, /ReactComponent/, /isReactComponent/, /react\.element/],
 sveltekit: [/data-sveltekit/, /x-sveltekit-/],
 svelte: [/window\.__svelte/, /svelte-announcer/],
 nuxt: [/_nuxt/, /window\.__NUXT__/],
 preact: [/globalThis\.preact/, /__PREACT_CLI_DATA__/],
 cloudflareanalytics: [/static\.cloudflareinsights\/.com/],
 webpack: [/window\.webpackJsonp/, /__webpack_require__/, /__webpack_module_/, /__webpack_exports__/],
 jquery: [/jquery\.org\/license/, /jquery-migrate/, /jquery.*(js)/],
 bootstrap: [/bootstrapcdn\.com/, /http:\/\/getbootstrap\.com/, /bootstrap\.min\.css/],
 astro: [/_astro/, /Astro v/],
 docusaurus: [/--docusaurus-/],
 googleanalytics: [/www\.googletagmanager\.com\/gtag\/js\?/, /www\.google-analytics\.com\/analytics\.js/],
 webflow: [/discourse\.webflow\.com\/t\//],
 koala: [/cdn\.getkoala\.com\//],
 jsdelivr: [/cdn\.jsdelivr\.net\//],
 hlsjs: [/\/hls*.js/, /.hljs{/],
 corejs: [/\/core-js\/internals\//],
 swiperjs: [/__swiper__/],
 weglot: [/cdn\.weglot\.com\/weglot/, /Weglot.initialize/],
 yahooads: [/yahoo_conversion_/, /yahoo_ss_/],
 unpkg: [/unpkg\.com\/.*\.[js,css]/],
 wordpress: [/\/cms\/wordpress\//],
 salesforce: [/"salesforce"/],
 gsap: [/_gsap/],
 carbonads: [/#carbonads/],
 alpinejs: [/window\.Alpine/],
 toastr: [/,toastr\['success'\]/],
 rechapta: [/\.grecaptcha-/],
 vimeoplayer: [/@vimeo\/player/, /data-vimeo-/],
 youtubeplayer: [/YouTubePlayer/],
 emotion: [/@emotion\/css/],
 angular: [/ng-bind/, /ng-version/],
 solidjs: [/Symbol\(\"solid-proxy\"\)/],
 quick: [/qwikloader/, /quickevents/],
 umami: [/analytics\.us\.umami\.is\/script\.js/],
 animatecss: [/animate\.css -http\:\/\/daneden\.me\/animate/, /\.animated{/],
 owlcarousel: [/\.owl-carousel/],
 lightbox: [/\.lb-disable-scrolling/, /\.lightboxOverlay{/],
 bootstrapicons: [/bootstrap-icons/],
 cdnjs: [/cdnjs\.cloudflare\.com/],
 sweetalert: [/\.[s,S]weet[a,A]lert/, /\.swalCloseEventFinishedCallback/, /\.swal2-popup/],
 googlemaps: [/maps\.googleapis\.com\/maps-api-/],
 katex: [/katex.*css/, /\.katex/],
 plausible: [/plausible\.io\/js\/plausible\.js/, /window\.plausible/, /nuxtjs\/plausible/],
 normalizecss: [/normalize\.css .* \| MIT License/, /\/normalize.*css/],
 prism: [/prismjs.*\/prism.*\.js/, /global\.Prism/, /u\.Prism/],
} as const;
export const namings = {
 cloudflareanalytics: { name: 'Cloudflare Browser Insights' },
 cloudinary: { name: 'Cloudinary' },
 fontawesome: { name: 'Font Awesome' },
 googlefonts: { name: 'Google Fonts' },
 lenis: { name: 'Lenis Scroll' },
 next: { name: 'Next.js' },
 nuxt: { name: 'Nuxt.js' },
 preact: { name: 'Preact' },
 react: { name: 'React' },
 svelte: { name: 'Svelte' },
 sveltekit: { name: 'SvelteKit' },
 tailwindcss: { name: 'Tailwind CSS' },
 vue: { name: 'Vue.js' },
 webpack: { name: 'Webpack' },
 astro: { name: 'Astro' },
 bootstrap: { name: 'Bootstrap CSS' },
 jquery: { name: 'jQuery' },
 docusaurus: { name: 'Docusaurus' },
 googleanalytics: { name: 'Google Analytics' },
 corejs: { name: 'core-js' },
 hlsjs: { name: 'Highlight.js' },
 yahooads: { name: 'Yahoo Advertising' },
 swiperjs: { name: 'Swiper' },
 jsdelivr: { name: 'jsDelivr CDN' },
 koala: { name: 'Koala Styles' },
 unpkg: { name: 'Unpkg CDN' },
 webflow: { name: 'Webflow Builder' },
 weglot: { name: 'Weglot i8n' },
 alpinejs: { name: 'Alpine.js' },
 carbonads: { name: 'Carbon Ads' },
 gsap: { name: 'GSAP' },
 rechapta: { name: 'reCHAPTA' },
 salesforce: { name: 'Salesforce' },
 toastr: { name: 'Toastr.js' },
 vimeoplayer: { name: 'Vimeo Player' },
 wordpress: { name: 'Wordpress' },
 youtubeplayer: { name: 'Youtube Player' },
 emotion: { name: 'Emotion CSS' },
 angular: { name: 'Angular' },
 solidjs: { name: 'SolidJS' },
 quick: { name: 'QuickJS' },
 umami: { name: 'Umami' },
 animatecss: { name: 'Animate.css' },
 owlcarousel: { name: 'Owl Carousel' },
 lightbox: { name: 'Lightbox' },
 bootstrapicons: { name: 'Bootstrap Icons' },
 cdnjs: { name: 'cdnjs' },
 googlemaps: { name: 'Google Maps' },
 sweetalert: { name: 'SweetAlert' },
 bulmacss: { name: 'Bulma CSS' },
 prism: { name: 'Prism.js' },
 katex: { name: 'KaTeX' },
 plausible: { name: 'Plausible Analytics' },
 normalizecss: { name: 'Normalize.css' },
} as Record<rawStack, { name: string; icon?: string }>;

export type rawStack = keyof typeof regexps;
