export const regexps = {
 next: [/_next/],
 googlefonts: [/fonts\.googleapis\.com/, /fonts\.gstatic\.com/],
 tailwindcss: [/MIT License | https:\/\/tailwindcss\.com/, /--tw-/],
 lenis: [/lenis/],
 cloudinary: [/res.cloudinary.com/],
 fontawesome: [/\/fontawesome/],
 vue: [/vue/],
 react: [/https:\/\/reactjs\.org\/docs\/error-decoder\.html/, /react\.forward_ref/, /__reactInternal/],
 sveltekit: [/data-sveltekit/, /x-sveltekit-/],
 svelte: [/window.__svelte/, /svelte-announcer/],
 nuxt: [/_nuxt/, /window\.__NUXT__/],
 preact: [/preact/],
 cloudflareanalytics: [/static\.cloudflareinsights\\.com/],
 webpack: [/window\.webpackJsonp/, /__webpack_require__/, /__webpack_module_/, /__webpack_exports__/],
 jquery: [/jquery.org\/license/, /jquery-migrate/, /jquery.*(js)/],
 bootstrap: [/bootstrapcdn\.com/, /http:\/\/getbootstrap\.com/],
 astro: [/_astro/, /Astro v/],
 docusaurus: [/--docusaurus-/],
 googleanalytics: [/https:\/\/www\.googletagmanager.com\/gtag\/js?/],
 webflow: [/https:\/\/discourse.webflow.com\/t\//],
 koala: [/https:\/\/cdn\.getkoala\.com\//],
 jsdelivr: [/https:\/\/cdn\.jsdelivr\.net\//],
 hlsjs: [/\/hls*.js/],
 corejs: [/\/core-js\/internals\//],
 swiperjs: [/__swiper__/],
 weglot: [/https:\/\/cdn\.weglot\.com\/weglot/, /Weglot.initialize/],
 yahooads: [/yahoo_conversion_/, /yahoo_ss_/],
 unpkg: [/https:\/\/unpkg\.com\/.*\.js/],
 wordpress: [/\/cms\/wordpress\//],
 salesforce: [/"salesforce"/],
 gsap: [/_gsap/],
 carbonads: [/#carbonads/],
 alpinejs: [/window\.Alpine/],
 toastr: [/,toastr\['success'\]/],
 rechapta: [/\.grecaptcha-/],
 vimeoplayer: [/@vimeo\/player/, /data-vimeo-/],
 youtubeplayer: [/YouTubePlayer/],
 emotion: [/@emotion\/css/],
 angular: [/ng-bind/],
 solidjs: [/Symbol\(\"solid-proxy\"\)/],
 quick: [/qwikloader/, /quickevents/],
 umami: [/analytics.us.umami.is\/script.js/],
} as const;
export type rawStack = keyof typeof regexps;
export default {
 cloudflareanalytics: { name: 'Cloudflare Browser Insights' },
 cloudinary: { name: 'Cloudinary' },
 fontawesome: { name: 'Font Awesome' },
 googlefonts: { name: 'Google Fonts' },
 lenis: { name: 'Lenis Scroll' },
 next: { name: 'Next.js' },
 nuxt: { name: 'Nuxt.js' },
 preact: { name: 'Preact' },
 react: { name: 'React' },
 svelte: { name: 'Svelte' },
 sveltekit: { name: 'SvelteKit' },
 tailwindcss: { name: 'Tailwind CSS' },
 vue: { name: 'Vue.js' },
 webpack: { name: 'Webpack' },
 astro: { name: 'Astro' },
 bootstrap: { name: 'Bootstrap CSS' },
 jquery: { name: 'jQuery' },
 docusaurus: { name: 'Docusaurus' },
 googleanalytics: { name: 'Google Analytics' },
 corejs: { name: 'core-js' },
 hlsjs: { name: 'HLS.js' },
 yahooads: { name: 'Yahoo Advertising' },
 swiperjs: { name: 'Swiper' },
 jsdelivr: { name: 'jsDelivr CDN' },
 koala: { name: 'Koala Styles' },
 unpkg: { name: 'Unpkg CDN' },
 webflow: { name: 'Webflow Builder' },
 weglot: { name: 'Weglot i8n' },
 alpinejs: { name: 'Alpine.js' },
 carbonads: { name: 'Carbon Ads' },
 gsap: { name: 'GSAP' },
 rechapta: { name: 'reCHAPTA' },
 salesforce: { name: 'Salesforce' },
 toastr: { name: 'Toastr.js' },
 vimeoplayer: { name: 'Vimeo Player' },
 wordpress: { name: 'Wordpress' },
 youtubeplayer: { name: 'Youtube Player' },
 emotion: { name: 'Emotion CSS' },
 angular: { name: 'Angular' },
 solidjs: { name: 'SolidJS' },
 quick: { name: 'QuickJS' },
 umami: { name: 'Umami' },
} satisfies Record<rawStack, { name: string; icon?: string }>;
